// Every user-facing UI string (CLAUDE.md §2, DESIGN.md §9). The UI ships in English this build;
// another language is a new file with the same shape. Two-line headings are [line1, line2].

export const en = {
  brand: 'KHATA',
  arrow: '→',

  nav: {
    ledger: 'Ledger',
    parties: 'Parties',
    scan: 'Scan',
    review: 'Review',
    settings: 'Settings',
    menu: 'Menu',
    close: 'Close',
    main: 'Main',
    reviewCount: (n: number) => `${n} to review`,
  },

  auth: {
    heading: ["Your shop's khata,", 'by voice.'],
    blurb: ["Speak an entry, scan a bill, ask what's owed.", 'Six Indian languages.'],
    sideLabel: 'Six languages, one ledger.',
    email: 'Email',
    password: 'Password',
    name: 'Your name',
    logIn: 'Log in',
    createAccount: 'Create account',
    toSignup: 'New here? Create an account',
    toLogin: 'Have an account? Log in',
    working: 'Working…',
    errors: {
      required: 'This field is required.',
      email: 'Enter an email address like name@example.com.',
      passwordShort: 'Use at least 6 characters.',
      badLogin: 'That email and password don’t match. Check both and try again.',
      exists: 'An account with this email already exists. Log in instead.',
      emailDisabled: 'Email login is turned off for this app. Ask the person who set it up.',
      generic: 'Could not reach the server. Check your internet and try again.',
    },
  },

  onboarding: {
    heading: ['Set up', 'your shop.'],
    languageHeading: ['Pick', 'your language.'],
    step: (n: number) => `Step ${n} of 2`,
    create: 'Create a shop',
    join: 'Join with code',
    shopName: 'Shop name',
    code: '6-character invite code',
    languageHelp: 'Spoken answers and read-backs use this language. You can change it in Settings.',
    next: 'Next',
    back: 'Back',
    createShop: 'Create shop',
    joinShop: 'Join shop',
    errors: {
      required: 'This field is required.',
      codeLength: 'The code has 6 characters.',
      pickLanguage: 'Pick a language to continue.',
    },
  },

  languages: {
    'ta-IN': 'தமிழ்',
    'hi-IN': 'हिन्दी',
    'en-IN': 'English',
    'te-IN': 'తెలుగు',
    'kn-IN': 'ಕನ್ನಡ',
    'ml-IN': 'മലയാളം',
  },

  // Placeholder screens show only their H2 until their step is built.
  screens: {
    ledger: ['Your', 'ledger.'],
    parties: ['Customers', 'and suppliers.'],
    partyDetail: ['Party', 'detail.'],
    review: ['Needs', 'a look.'],
    entry: ['Edit', 'entry.'],
    scan: ['What kind', 'of bill?'],
    settings: ['Your', 'settings.'],
    logOut: 'Log out',
  },

  status: {
    confirmed: 'Confirmed',
    pending: 'Pending',
    voided: 'Voided',
    auto: 'Auto',
    new: 'New',
  },

  ledger: {
    holdToAdd: 'Hold to add',
    holdToAsk: 'Hold to ask',
    holdToAnswer: 'Hold to answer',
    scanBill: 'Scan a bill',
    listening: 'Listening… release to send',
    working: 'Working…',
    tooShort: 'Hold the button while speaking.',
    recent: ['Recent', 'entries.'],
    empty: ['Hold ADD and say what happened,', 'like ‘Ramesh took 250 on credit’.'],
    confirm: 'Confirm',
    edit: 'Edit',
    voidIt: 'Void',
    yesName: (name: string) => `Yes, ${name}`,
    didYouMean: (name: string) => `Did you mean ${name}?`,
    noNewPerson: 'No, new person',
    addByHand: 'Add by hand',
    closeForm: 'Close form',
    type: 'Type',
    amount: 'Amount (₹)',
    partyName: 'Customer or supplier name',
    note: 'Note',
    save: 'Save entry',
    saved: (who: string, amount: string) => `Saved · ${who} · ${amount}`,
    heard: (text: string) => `Heard: “${text}”`,
    play: 'Play',
    noParty: '—',
  },

  mic: {
    heading: ['Microphone', 'is blocked.'],
    lead: 'Khata needs the microphone to hear entries and questions. Nothing is recorded until you hold a button.',
    steps: [
      'Tap the lock or settings icon next to the web address.',
      'Find Microphone and choose Allow.',
      'Come back here and tap Try again.',
    ],
    retry: 'Try again',
    close: 'Close',
  },

  landing: {
    nav: { home: 'Home', how: 'How it works', login: 'Log in', start: 'Get started' },
    hero: ['Your khata,', 'by voice.'],
    blurb: ["Speak an entry, scan a bill, ask what's owed.", 'Six Indian languages.'],
    start: 'Get started',
    howTitle: ['Three ways', 'to keep the book.'],
    ways: [
      { title: 'Speak it', body: ['Hold, say who took what.', "It's written down."] },
      { title: 'Scan it', body: ['Photograph any bill,', 'printed or handwritten.'] },
      { title: 'Ask it', body: ['‘How much does Ramesh owe?’', 'Answered aloud.'] },
    ],
    trustTitle: ['Built to', 'be trusted.'],
    principles: ['Every entry keeps its recording.', 'Big amounts always wait for your tap.', 'Six languages, one ledger.'],
    sayTitle: ['Say it', 'your way.'],
    // TODO: native-speaker check. Each line should be how a shopkeeper would actually say
    // "I gave Ramesh 250 on credit" in that language, in its own script.
    sayLines: [
      { said: 'ரமேஷுக்கு 250 ரூபாய் கடன் கொடுத்தேன்', lang: 'Tamil', code: 'ta' },
      { said: 'रमेश को 250 उधार दिया', lang: 'Hindi', code: 'hi' },
      { said: 'Gave Ramesh 250 on credit', lang: 'English', code: 'en' },
      { said: 'రమేష్‌కి 250 రూపాయలు అప్పు ఇచ్చాను', lang: 'Telugu', code: 'te' },
      { said: 'ರಮೇಶ್‌ಗೆ 250 ರೂಪಾಯಿ ಸಾಲ ಕೊಟ್ಟೆ', lang: 'Kannada', code: 'kn' },
      { said: 'രമേശിന് 250 രൂപ കടം കൊടുത്തു', lang: 'Malayalam', code: 'ml' },
    ],
    builtByTitle: ['Built', 'by.'],
    // TODO: the maker's 4-line bio. BuiltBy renders only when public/founder.jpg exists.
    builtByBio: [] as string[],
    footerLinks: [
      { label: 'Log in', to: '/login' },
      { label: 'Create an account', to: '/signup' },
      { label: 'Try the demo', to: '/demo' },
      { label: 'How it works in detail', to: '/about' },
    ],
    builtFor: 'Built for a hackathon, September 2026.',
    repoLabel: 'github.com/maanit-gupta/KHATA',
    repoUrl: 'https://github.com/maanit-gupta/KHATA',
    founderAlt: 'The maker of Khata',
  },

  about: {
    navDemo: 'Try demo',
    navLogin: 'Log in',
    hero: ['How Khata', 'works.'],
    intro:
      'Khata is a ledger for kirana and small shops. Say an entry out loud or photograph a bill, and Khata writes it into the book, matches the right customer or supplier, and reads it back in your language.',
    flowTitle: ['Two ways', 'in.'],
    flows: [
      {
        label: 'Speak it',
        title: 'Hold, say it, release.',
        steps: [
          'Hold the button and say who took what, for example “Ramesh ko 250 udhaar diya”. Up to 30 seconds.',
          'The recording is stored privately, then Sarvam turns the speech into English text.',
          'Groq reads that text and pulls out the type, the person and the amount as strict JSON.',
          'The name is matched against your customers or suppliers, and the save rules below decide what happens.',
          'Khata speaks the result back in your language: “Ramesh, 250 rupees udhaar, saved.”',
        ],
      },
      {
        label: 'Scan it',
        title: 'Photograph the bill.',
        steps: [
          'Tap what kind of bill it is: Supplier, Customer or Expense.',
          'Say how it was settled: Paid or Credit for suppliers, Cash or Udhaar for customers.',
          'Take or upload a photo. Sarvam Document AI reads the vendor, the date and the total.',
          'Check the three fields and fix anything before saving. If the bill can’t be read, type them in.',
          'The bill becomes an entry of the right type, and the same save rules apply.',
        ],
      },
    ],
    rulesTitle: ['Who decides', 'what’s saved.'],
    rulesLead:
      'Not the AI. The model only reads what was said. A small set of fixed rules, written in plain code, decides whether an entry is saved, waits for you, or is asked again.',
    rules: [
      { when: 'No amount, or no name where one is needed', result: 'Asks again', status: 'unselected' },
      { when: 'The name clearly matches one customer or supplier', result: 'Uses them', status: 'confirmed' },
      { when: 'The name is close to someone, but not certain', result: 'Did you mean…?', status: 'pending' },
      { when: 'A name Khata has never heard', result: 'New, flagged', status: 'confirmed' },
      { when: 'More than ₹5,000', result: 'Waits for a tap', status: 'pending' },
      { when: 'Everything else', result: 'Saved, 5 s undo', status: 'confirmed' },
    ],
    legend: { saved: 'Saved', pending: 'Waits for you', nothing: 'Nothing saved' },
    trustTitle: ['Built to', 'be trusted.'],
    trust: [
      { title: 'Every entry keeps its evidence', body: 'The voice note or bill photo stays with the entry, in private storage, for disputes later.' },
      { title: 'Nothing is ever deleted', body: 'A wrong entry is voided, not erased, and every edit is recorded with who made it and what changed.' },
      { title: 'Big amounts wait for you', body: 'Anything over ₹5,000 is held as pending until someone in the shop taps Confirm.' },
      { title: 'Your shop only', body: 'Database row-level security means a member can only ever read their own shop’s book.' },
      { title: 'Numbers are checked twice', body: 'Read-backs are translated into your language, and if a number changes on the way, Khata says it in English instead.' },
      { title: 'Money in whole paise', body: 'Amounts are stored as whole paise, not decimals, and balances are always worked out from the entries themselves.' },
    ],
    langTitle: ['Say it', 'your way.'],
    langLead: 'Each person in the shop picks their own language. Speech and spoken answers use it; names are kept exactly as entered.',
    examples: [
      { said: 'रमेश को 250 उधार दिया', lang: 'Hindi' },
      { said: 'ரமேஷுக்கு 250 ரூபாய் கடன் கொடுத்தேன்', lang: 'Tamil' },
      { said: 'రమేష్‌కి 250 రూపాయలు అప్పు ఇచ్చాను', lang: 'Telugu' },
      { said: 'ರಮೇಶ್‌ಗೆ 250 ರೂಪಾಯಿ ಸಾಲ ಕೊಟ್ಟೆ', lang: 'Kannada' },
      { said: 'രമേശിന് 250 രൂപ കടം കൊടുത്തു', lang: 'Malayalam' },
      { said: 'Gave Ramesh 250 on credit', lang: 'English' },
    ],
    stackTitle: ['What it’s', 'made of.'],
    stack: [
      ['Speech & bills', 'Sarvam AI: saaras:v3 speech-to-text, mayura translation, bulbul:v3 voices, Document AI extract'],
      ['Understanding', 'Groq running gpt-oss-20b for reading entries, gpt-oss-120b for answering questions'],
      ['Data & accounts', 'Supabase: Postgres with row-level security, email login, private file storage'],
      ['App', 'React and Vite on Vercel, a FastAPI (Python) backend on Render'],
    ],
    ctaTitle: ['See it', 'for yourself.'],
    ctaBody: 'The demo opens a sample shop in your browser. No account needed, and nothing you do is saved.',
    ctaDemo: 'Try the demo',
    ctaSignup: 'Create an account',
    repo: 'Source on GitHub',
    repoUrl: 'https://github.com/maanit-gupta/KHATA',
    link: 'How it works',
  },

  demo: {
    try: 'Try the demo, no account needed',
    banner: 'Demo mode: sample shop, nothing is saved. Voice and bill reading are simulated.',
    exit: 'Exit demo',
  },

  scan: {
    kindHeading: ['What kind', 'of bill?'],
    settleHeading: ['How was it', 'settled?'],
    photoHeading: ['Photograph', 'the bill.'],
    checkHeading: ['Check', 'the bill.'],
    doneHeading: ['Bill', 'saved.'],
    supplier: 'Supplier',
    customer: 'Customer',
    expense: 'Expense',
    kindHelp: {
      supplier: 'Stock you bought from a wholesaler.',
      customer: 'A bill you gave to a customer.',
      expense: 'Rent, power, wages and other costs.',
    },
    paid: 'Paid',
    credit: 'Credit',
    cash: 'Cash',
    udhaar: 'Udhaar',
    photo: 'Take or choose a photo',
    photoHelp: 'JPG or PNG, up to 10 MB.',
    reading: 'Reading the bill…',
    typeByHand: 'Type the values from the bill.',
    vendor: 'Vendor',
    date: 'Bill date',
    total: 'Total (₹)',
    customerName: 'Customer name',
    save: 'Save entry',
    saved: 'Saved.',
    pending: 'Waiting for a tap. Confirm it here or in Review.',
    another: 'Scan another bill',
    back: 'Back',
    toLedger: 'Back to the ledger',
    preview: 'Photo of the bill',
  },

  entryTypes: {
    credit_given: 'Credit given',
    payment_received: 'Payment received',
    cash_sale: 'Cash sale',
    purchase_credit: 'Purchase on credit',
    purchase_paid: 'Purchase paid',
    payment_made: 'Payment made',
    expense: 'Expense',
  },

  parties: {
    owesYou: (amount: string) => `Owes you ${amount}`,
    youOwe: (amount: string) => `You owe ${amount}`,
    settled: 'Settled',
    empty: 'No customers or suppliers yet. They appear when you add an entry.',
    noMatch: 'Nobody by that name.',
    back: 'All parties',
    search: 'Search by name',
    filter: 'Show customers or suppliers',
    customers: 'Customers',
    suppliers: 'Suppliers',
    playRecording: 'Play the recording',
    openBill: 'Open the bill photo',
    noEntries: 'No entries yet.',
    customer: 'Customer',
    supplier: 'Supplier',
  },

  week: {
    heading: ['This week,', 'so far.'],
    cash: 'Cash sales',
    credit: 'Credit given',
    collected: 'Collected',
    expenses: 'Expenses',
    lastWeek: (amount: string) => `Last week, Mon–Sun: ${amount}`,
    debtors: 'Owes the most',
    days: (n: number | null) => (n === null ? '' : n === 0 ? 'Last entry today' : n === 1 ? 'Last entry 1 day ago' : `Last entry ${n} days ago`),
    play: 'Play the summary',
  },

  review: {
    pendingTitle: 'Waiting for a tap',
    partiesTitle: 'New people',
    receiptsTitle: 'Bills that could not be read',
    empty: 'Nothing needs a look right now.',
    rename: 'Rename',
    mergeInto: 'Merge into…',
    keep: 'Keep as is',
    saveName: 'Save name',
    cancel: 'Cancel',
    newName: 'New name',
    mergePick: (name: string) => `Merge ${name} into:`,
    noMergeTarget: 'There is nobody of the same kind to merge into.',
    merged: (from: string, into: string) => `Merged ${from} into ${into}.`,
    enterManually: 'Enter manually',
    unreadBill: (kind: string) => `${kind} bill`,
  },

  entry: {
    heading: ['Edit', 'entry.'],
    saveChanges: 'Save changes',
    saved: 'Changes saved.',
    party: 'Customer or supplier',
    date: 'Date',
    historyTitle: 'History',
    you: 'You',
    another: 'Another member',
    actions: { create: 'Created', edit: 'Edited', confirm: 'Confirmed', void: 'Voided' } as Record<string, string>,
    fields: {
      amount_paise: 'Amount', type: 'Type', party: 'Party', occurred_on: 'Date', note: 'Note', status: 'Status',
    } as Record<string, string>,
    voidEntry: 'Void entry',
    voidConfirmTitle: 'Void this entry?',
    voidConfirmBody: 'It stops counting in balances and totals. It stays in the history and can’t be edited after.',
    voidYes: 'Yes, void it',
    keepIt: 'Keep it',
    voided: 'This entry is voided. It no longer counts.',
    source: { voice: 'Spoken', receipt: 'From a bill', manual: 'Typed' } as Record<string, string>,
    none: 'none',
  },

  settings: {
    language: 'My language',
    languageHelp: 'Spoken read-backs and answers use this language.',
    voice: 'Voice',
    voiceHelp: 'Tap a voice to hear it.',
    defaultVoice: 'Default',
    sample: 'Ramesh owes you 250 rupees.',
    invite: 'Shop invite code',
    inviteHelp: 'Anyone with this code can join your shop.',
    copy: 'Copy',
    copied: 'Copied',
    logOut: 'Log out',
    shop: 'Shop',
  },

  toast: {
    undo: 'Undo',
    undone: 'Undone.',
  },

  errors: {
    loading: 'Loading…',
    notFound: 'That page does not exist.',
    waking: 'Waking the server…',
    wakingHelp: 'The first request after a quiet spell can take up to a minute.',
  },

  offline: {
    heading: ['No internet.', 'Entries can’t be saved right now.'],
    retry: 'Retry',
    still: 'Still no connection. Check your internet, then retry.',
    network: 'No internet. Entries can’t be saved right now.',
  },
} as const

export type Lang = keyof typeof en.languages
export const LANG_ORDER: Lang[] = ['ta-IN', 'hi-IN', 'en-IN', 'te-IN', 'kn-IN', 'ml-IN']

export const t = en
