// Every user-facing UI string, English (CLAUDE.md §2, DESIGN.md §9). Each other UI language is a file
// with exactly the same keys (strings/index.ts checks it at compile time; GOAL_2.0 P5.2).
// Two-line headings are [line1, line2].

export const en = {
  brand: 'KHATA',
  arrow: '→',

  nav: {
    home: 'Home',
    ledger: 'Ledger',
    dashboard: 'Dashboard',
    parties: 'Parties',
    scan: 'Scan',
    review: 'Review',
    settings: 'Settings',
    menu: 'Menu',
    close: 'Close',
    main: 'Main',
    reviewCount: (n: number) => `${n} to review`,
  },

  auth: {
    heading: ["Your shop's khata,", 'by voice.'],
    blurb: ["Speak an entry, scan a bill, ask what's owed.", 'Six Indian languages.'],
    sideLabel: 'Six languages, one ledger.',
    email: 'Email',
    password: 'Password',
    name: 'Your name',
    logIn: 'Log in',
    createAccount: 'Create account',
    toSignup: 'New here? Create an account',
    toLogin: 'Have an account? Log in',
    working: 'Working…',
    errors: {
      required: 'This field is required.',
      email: 'Enter an email address like name@example.com.',
      passwordShort: 'Use at least 6 characters.',
      badLogin: 'That email and password don’t match. Check both and try again.',
      exists: 'An account with this email already exists. Log in instead.',
      emailDisabled: 'Email login is turned off for this app. Ask the person who set it up.',
      generic: 'Could not reach the server. Check your internet and try again.',
    },
  },

  onboarding: {
    heading: ['Set up', 'your shop.'],
    languageHeading: ['Pick', 'your language.'],
    step: (n: number) => `Step ${n} of 2`,
    create: 'Create a shop',
    join: 'Join with code',
    shopName: 'Shop name',
    code: '6-character invite code',
    languageHelp: 'Khata listens, speaks and shows its screens in this language. In Settings you can pick each of these separately.',
    next: 'Next',
    back: 'Back',
    createShop: 'Create shop',
    joinShop: 'Join shop',
    errors: {
      required: 'This field is required.',
      codeLength: 'The code has 6 characters.',
      pickLanguage: 'Pick a language to continue.',
    },
  },

  languages: {
    'ta-IN': 'தமிழ்',
    'hi-IN': 'हिन्दी',
    'en-IN': 'English',
    'te-IN': 'తెలుగు',
    'kn-IN': 'ಕನ್ನಡ',
    'ml-IN': 'മലയാളം',
  },

  // Placeholder screens show only their H2 until their step is built.
  screens: {
    ledger: ['Your', 'ledger.'],
    parties: ['Customers', 'and suppliers.'],
    partyDetail: ['Party', 'detail.'],
    review: ['Needs', 'a look.'],
    entry: ['Edit', 'entry.'],
    scan: ['What kind', 'of bill?'],
    settings: ['Your', 'settings.'],
  },

  status: {
    confirmed: 'Confirmed',
    pending: 'Pending',
    voided: 'Voided',
    auto: 'Auto',
    new: 'New',
  },

  ledger: {
    holdToAdd: 'Hold to add',
    holdToAsk: 'Hold to ask',
    holdToAnswer: 'Hold to answer',
    scanBill: 'Scan a bill',
    listening: 'Listening… release to send',
    working: 'Working…',
    tooShort: 'Hold the button while speaking.',
    recent: ['Recent', 'entries.'],
    empty: ['Hold ADD and say what happened,', 'like ‘Ramesh took 250 on credit’.'],
    confirm: 'Confirm',
    edit: 'Edit',
    voidIt: 'Void',
    yesName: (name: string) => `Yes, ${name}`,
    didYouMean: (name: string) => `Did you mean ${name}?`,
    noNewPerson: 'No, new person',
    addByHand: 'Add by hand',
    closeForm: 'Close form',
    type: 'Type',
    amount: 'Amount (₹)',
    partyName: 'Customer or supplier name',
    note: 'Note',
    save: 'Save entry',
    saved: (who: string, amount: string) => `Saved · ${who} · ${amount}`,
    whatIHeard: 'What I heard',
    heardNothing: 'Nothing. The recording was silent.',
    play: 'Play',
    noParty: '—',
  },

  // GOAL_2.0 P3.1: the whole book as a table.
  table: {
    heading: ['The whole', 'book.'],
    presets: { all: 'All', today: 'Today', week: 'This week', month: 'This month', custom: 'Custom' },
    period: 'Period',
    from: 'From',
    to: 'To',
    type: 'Type',
    allTypes: 'All types',
    party: 'Party',
    allParties: 'Everyone',
    source: 'Source',
    allSources: 'Any source',
    member: 'Added by',
    allMembers: 'Anyone',
    show: 'Show',
    search: 'Search names and notes',
    cols: { date: 'Date', party: 'Party', type: 'Type', amount: 'Amount', source: 'Source', addedBy: 'Added by', status: 'Status' },
    sources: { voice: 'Voice', receipt: 'Bill', manual: 'Typed' } as Record<string, string>,
    totals: { cashIn: 'Cash in', credit: 'Credit given', collected: 'Collected', expenses: 'Expenses',
      note: 'Totals count confirmed entries only.' },
    count: (n: number) => (n === 1 ? '1 entry' : `${n} entries`),
    page: (p: number, n: number) => `Page ${p} of ${n}`,
    prev: 'Previous',
    next: 'Next',
    export: 'Download CSV',
    exporting: 'Preparing…',
    empty: 'No entries match these filters. Clear them, or add one by hand.',
    clear: 'Clear filters',
    caption: 'Ledger entries, newest first',
    open: (what: string) => `Open ${what}`,
  },

  // GOAL_2.0 P3.4: quick manual add.
  manual: {
    date: 'Date',
    matches: 'Matching names',
    savedAddAnother: 'Saved. Add another.',
  },

  mic: {
    heading: ['Microphone', 'is blocked.'],
    lead: 'Khata needs the microphone to hear entries and questions. Nothing is recorded until you hold a button.',
    steps: [
      'Tap the lock or settings icon next to the web address.',
      'Find Microphone and choose Allow.',
      'Come back here and tap Try again.',
    ],
    retry: 'Try again',
    close: 'Close',
  },

  landing: {
    nav: { home: 'Home', how: 'How it works', login: 'Log in', start: 'Get started' },
    hero: ['Your khata,', 'by voice.'],
    blurb: ["Speak an entry, scan a bill, ask what's owed.", 'Six Indian languages.'],
    start: 'Get started',
    howTitle: ['Three ways', 'to keep the book.'],
    ways: [
      { title: 'Speak it', body: ['Hold, say who took what.', "It's written down."] },
      { title: 'Scan it', body: ['Photograph any bill,', 'printed or handwritten.'] },
      { title: 'Ask it', body: ['‘How much does Ramesh owe?’', 'Answered aloud.'] },
    ],
    trustTitle: ['Built to', 'be trusted.'],
    principles: ['Every entry keeps its recording.', 'Big amounts always wait for your tap.', 'Six languages, one ledger.'],
    sayTitle: ['Say it', 'your way.'],
    // TODO: native-speaker check. Each line should be how a shopkeeper would actually say
    // "I gave Ramesh 250 on credit" in that language, in its own script.
    sayLines: [
      { said: 'ரமேஷுக்கு 250 ரூபாய் கடன் கொடுத்தேன்', lang: 'Tamil', code: 'ta' },
      { said: 'रमेश को 250 उधार दिया', lang: 'Hindi', code: 'hi' },
      { said: 'Gave Ramesh 250 on credit', lang: 'English', code: 'en' },
      { said: 'రమేష్‌కి 250 రూపాయలు అప్పు ఇచ్చాను', lang: 'Telugu', code: 'te' },
      { said: 'ರಮೇಶ್‌ಗೆ 250 ರೂಪಾಯಿ ಸಾಲ ಕೊಟ್ಟೆ', lang: 'Kannada', code: 'kn' },
      { said: 'രമേശിന് 250 രൂപ കടം കൊടുത്തു', lang: 'Malayalam', code: 'ml' },
    ],
    builtByTitle: ['Built', 'by.'],
    // TODO: the maker's 4-line bio. BuiltBy renders only when public/founder.jpg exists.
    builtByBio: [] as string[],
    footerLinks: [
      { label: 'Log in', to: '/login' },
      { label: 'Create an account', to: '/signup' },
      { label: 'How it works in detail', to: '/about' },
    ],
    builtFor: 'Built for Sarvam Campus Builds, September 2026.',
    repoLabel: 'github.com/maanit-gupta/KHATA',
    repoUrl: 'https://github.com/maanit-gupta/KHATA',
    founderAlt: 'The maker of Khata',
  },

  about: {
    navSignup: 'Sign up',
    navLogin: 'Log in',
    hero: ['How Khata', 'works.'],
    intro:
      'Khata is a ledger for kirana and small shops. Say an entry out loud or photograph a bill, and Khata writes it into the book, matches the right customer or supplier, and reads it back in your language.',
    flowTitle: ['Two ways', 'in.'],
    flows: [
      {
        label: 'Speak it',
        title: 'Hold, say it, release.',
        steps: [
          'Hold the button and say who took what, for example “Ramesh ko 250 udhaar diya”. Up to 30 seconds.',
          'The recording is stored privately, then Sarvam turns the speech into English text.',
          'Groq reads that text and pulls out the type, the person and the amount as strict JSON.',
          'The name is matched against your customers or suppliers, and the save rules below decide what happens.',
          'Khata speaks the result back in your language: “Ramesh, 250 rupees udhaar, saved.”',
        ],
      },
      {
        label: 'Scan it',
        title: 'Photograph the bill.',
        steps: [
          'Tap what kind of bill it is: Supplier, Customer or Expense.',
          'Say how it was settled: Paid or Credit for suppliers, Cash or Udhaar for customers.',
          'Take or upload a photo. Sarvam Document AI reads the vendor, the date and the total.',
          'Check the three fields and fix anything before saving. If the bill can’t be read, type them in.',
          'The bill becomes an entry of the right type, and the same save rules apply.',
        ],
      },
    ],
    rulesTitle: ['Who decides', 'what’s saved.'],
    rulesLead:
      'Not the AI. The model only reads what was said. A small set of fixed rules, written in plain code, decides whether an entry is saved, waits for you, or is asked again.',
    rules: [
      { when: 'No amount, or no name where one is needed', result: 'Asks again', status: 'unselected' },
      { when: 'The name clearly matches one customer or supplier', result: 'Uses them', status: 'confirmed' },
      { when: 'The name is close to someone, but not certain', result: 'Did you mean…?', status: 'pending' },
      { when: 'A name Khata has never heard', result: 'New, flagged', status: 'confirmed' },
      { when: 'More than ₹5,000', result: 'Waits for a tap', status: 'pending' },
      { when: 'Everything else', result: 'Saved, 5 s undo', status: 'confirmed' },
    ],
    legend: { saved: 'Saved', pending: 'Waits for you', nothing: 'Nothing saved' },
    trustTitle: ['Built to', 'be trusted.'],
    trust: [
      { title: 'Every entry keeps its evidence', body: 'The voice note or bill photo stays with the entry, in private storage, for disputes later.' },
      { title: 'Nothing is ever deleted', body: 'A wrong entry is voided, not erased, and every edit is recorded with who made it and what changed.' },
      { title: 'Big amounts wait for you', body: 'Anything over ₹5,000 is held as pending until someone in the shop taps Confirm.' },
      { title: 'Your shop only', body: 'Database row-level security means a member can only ever read their own shop’s book.' },
      { title: 'Numbers are checked twice', body: 'Read-backs are translated into your language, and if a number changes on the way, Khata says it in English instead.' },
      { title: 'Money in whole paise', body: 'Amounts are stored as whole paise, not decimals, and balances are always worked out from the entries themselves.' },
    ],
    langTitle: ['Say it', 'your way.'],
    langLead: 'Each person in the shop picks their own language. Speech and spoken answers use it; names are kept exactly as entered.',
    examples: [
      { said: 'रमेश को 250 उधार दिया', lang: 'Hindi' },
      { said: 'ரமேஷுக்கு 250 ரூபாய் கடன் கொடுத்தேன்', lang: 'Tamil' },
      { said: 'రమేష్‌కి 250 రూపాయలు అప్పు ఇచ్చాను', lang: 'Telugu' },
      { said: 'ರಮೇಶ್‌ಗೆ 250 ರೂಪಾಯಿ ಸಾಲ ಕೊಟ್ಟೆ', lang: 'Kannada' },
      { said: 'രമേശിന് 250 രൂപ കടം കൊടുത്തു', lang: 'Malayalam' },
      { said: 'Gave Ramesh 250 on credit', lang: 'English' },
    ],
    stackTitle: ['What it’s', 'made of.'],
    stack: [
      ['Speech & bills', 'Sarvam AI: saaras:v3 speech-to-text, mayura translation, bulbul:v3 voices, Document AI extract'],
      ['Understanding', 'Groq running gpt-oss-20b for reading entries, gpt-oss-120b for answering questions'],
      ['Data & accounts', 'Supabase: Postgres with row-level security, email login, private file storage'],
      ['App', 'React and Vite on Vercel, a FastAPI (Python) backend on Render'],
    ],
    ctaTitle: ['See it', 'for yourself.'],
    ctaBody: 'Create an account, set up your shop, and hold ADD to say your first entry.',
    ctaSignup: 'Create an account',
    repo: 'Source on GitHub',
    repoUrl: 'https://github.com/maanit-gupta/KHATA',
    link: 'How it works',
  },

  scan: {
    kindHeading: ['What kind', 'of bill?'],
    settleHeading: ['How was it', 'settled?'],
    photoHeading: ['Photograph', 'the bill.'],
    previewHeading: ['Is the bill', 'clear?'],
    readingHeading: ['Reading', 'the bill.'],
    checkHeading: ['Check', 'the bill.'],
    doneHeading: ['Bill', 'saved.'],
    supplier: 'Supplier',
    customer: 'Customer',
    expense: 'Expense',
    kindHelp: {
      supplier: 'Stock you bought from a wholesaler.',
      customer: 'A bill you gave to a customer.',
      expense: 'Rent, power, wages and other costs.',
    },
    paid: 'Paid',
    credit: 'Credit',
    cash: 'Cash',
    udhaar: 'Udhaar',
    takePhoto: 'Take a photo',
    fromGallery: 'Upload from gallery',
    chooseFile: 'Choose a file',
    dropHere: 'Drop a photo or PDF of the bill here',
    photoHelp: 'JPG, PNG, HEIC or a one-page PDF, up to 10 MB.',
    errors: {
      type: 'That file isn’t a photo or a PDF. Use a JPG, PNG, HEIC or PDF of the bill.',
      heic: 'This browser can’t open HEIC photos. Tap Take a photo instead, or on the iPhone set Settings → Camera → Formats → Most Compatible.',
      size: 'That file is over 10 MB. Use a smaller photo.',
      decode: 'That photo couldn’t be opened. Take it again.',
    },
    rotate: 'Turn 90°',
    retake: 'Retake',
    usePhoto: 'Use this photo',
    tooDarkOrSmall: 'Photo too dark or small; retake for better reading.',
    pdfFile: (name: string) => `PDF · ${name}`,
    steps: { uploading: 'Uploading', reading: 'Reading the bill', checking: 'Checking' },
    cancel: 'Cancel',
    slow: 'This is taking longer than usual.',
    typeItIn: 'Type it in instead',
    typeByHand: 'Type the values from the bill.',
    vendor: 'Vendor',
    date: 'Bill date',
    total: 'Total (₹)',
    customerName: 'Customer name',
    notFound: 'Not found, please type.',
    dateNotFound: 'Not found on the bill; today’s date is filled in.',
    checkThis: 'Check this: this total isn’t printed on the bill as read.',
    changeKind: 'Bill kind',
    save: 'Save entry',
    saved: 'Saved.',
    pending: 'Waiting for a tap. Confirm it here or in Review.',
    another: 'Another bill',
    back: 'Back',
    toLedger: 'Back to the ledger',
    preview: 'Photo of the bill',
    enlarge: 'Enlarge the photo',
    shrink: 'Make the photo smaller',
    whatIRead: 'What I read',
    readNothing: 'No text could be read from this photo.',
  },

  entryTypes: {
    credit_given: 'Credit given',
    payment_received: 'Payment received',
    cash_sale: 'Cash sale',
    purchase_credit: 'Purchase on credit',
    purchase_paid: 'Purchase paid',
    payment_made: 'Payment made',
    expense: 'Expense',
  },

  parties: {
    owesYou: (amount: string) => `Owes you ${amount}`,
    youOwe: (amount: string) => `You owe ${amount}`,
    settled: 'Settled',
    empty: 'No customers or suppliers yet. They appear when you add an entry.',
    noMatch: 'Nobody by that name.',
    back: 'All parties',
    search: 'Search by name',
    filter: 'Show customers or suppliers',
    customers: 'Customers',
    suppliers: 'Suppliers',
    playRecording: 'Play the recording',
    openBill: 'Open the bill photo',
    noEntries: 'No entries yet.',
    customer: 'Customer',
    supplier: 'Supplier',
    statement: {
      title: 'Statement',
      from: 'From',
      to: 'To',
      cols: { date: 'Date', description: 'Description', change: '+ / −', balance: 'Balance after' },
      opening: 'Opening balance',
      closing: 'Closing balance',
      share: 'Share statement',
      empty: 'No confirmed entries in these dates.',
      caption: (name: string) => `Statement for ${name}, oldest first`,
      help: '+ means they owe the shop more; − means less. Confirmed entries only.',
    },
    entriesTitle: 'Entries',
  },

  week: {
    heading: ['This week,', 'so far.'],
    cash: 'Cash sales',
    credit: 'Credit given',
    collected: 'Collected',
    expenses: 'Expenses',
    lastWeek: (amount: string) => `Last week, Mon–Sun: ${amount}`,
    debtors: 'Owes the most',
    days: (n: number | null) => (n === null ? '' : n === 0 ? 'Last entry today' : n === 1 ? 'Last entry 1 day ago' : `Last entry ${n} days ago`),
    play: 'Play the summary',
  },

  review: {
    pendingTitle: 'Waiting for a tap',
    partiesTitle: 'New people',
    receiptsTitle: 'Bills that could not be read',
    empty: 'Nothing needs a look right now.',
    rename: 'Rename',
    mergeInto: 'Merge into…',
    keep: 'Keep as is',
    saveName: 'Save name',
    cancel: 'Cancel',
    newName: 'New name',
    mergePick: (name: string) => `Merge ${name} into:`,
    noMergeTarget: 'There is nobody of the same kind to merge into.',
    merged: (from: string, into: string) => `Merged ${from} into ${into}.`,
    enterManually: 'Enter manually',
    unreadBill: (kind: string) => `${kind} bill`,
  },

  entry: {
    heading: ['Edit', 'entry.'],
    saveChanges: 'Save changes',
    saved: 'Changes saved.',
    party: 'Customer or supplier',
    date: 'Date',
    historyTitle: 'History',
    actions: { create: 'Created', edit: 'Edited', confirm: 'Confirmed', void: 'Voided' } as Record<string, string>,
    fields: {
      amount_paise: 'Amount', type: 'Type', party: 'Party', occurred_on: 'Date', note: 'Note', status: 'Status',
    } as Record<string, string>,
    addedBy: (name: string) => `Added by ${name}`,
    confirmedBy: (name: string) => `Confirmed by ${name}`,
    voidEntry: 'Void entry',
    voidConfirmTitle: 'Void this entry?',
    voidConfirmBody: 'It stops counting in balances and totals. It stays in the history and can’t be edited after.',
    voidYes: 'Yes, void it',
    keepIt: 'Keep it',
    voided: 'This entry is voided. It no longer counts.',
    source: { voice: 'Spoken', receipt: 'From a bill', manual: 'Typed' } as Record<string, string>,
    none: 'none',
  },

  settings: {
    // GOAL_2.0 P5.1: a language for each aspect, chosen separately.
    languages: {
      title: 'Languages',
      help: 'Choose each one separately. Changes apply at once.',
      ui: 'On-screen text',
      uiHelp: 'Buttons, labels and messages.',
      speak: 'I speak in',
      speakHelp: 'The language you talk to Khata in.',
      auto: 'Detect automatically',
      autoHelp: 'Khata works out which language you spoke.',
      voice: 'Read-backs and answers in',
      voiceHelp: 'What Khata says out loud.',
      report: 'Summaries and reports in',
      reportHelp: 'The weekly summary, tips, the daily briefing and PDF reports.',
    },
    voice: 'Voice',
    voiceHelp: 'Tap a voice to hear it.',
    defaultVoice: 'Default',
    sample: 'Ramesh owes you 250 rupees.',
    invite: 'Shop invite code',
    inviteHelp: 'Anyone with this code can join your shop.',
    copy: 'Copy',
    copied: 'Copied',
    logOut: 'Log out',
    shop: 'Shop',
    name: 'My name',
    nameHelp: 'Everyone in the shop sees this next to what you add or change.',
    saveName: 'Save name',
    nameSaved: 'Name saved.',
    members: 'People in this shop',
    roles: { owner: 'Owner', staff: 'Staff' } as Record<string, string>,
    joined: (day: string) => `Joined ${day}`,
    sameRights: 'Everyone in the shop can do the same things.',
  },

  // GOAL_2.0 P4: the activity feed.
  activity: {
    title: 'What happened',
    empty: 'Nothing yet. Every entry added, changed, confirmed or voided shows up here, with who did it.',
    verbs: { create: 'added', edit: 'changed', confirm: 'confirmed', void: 'voided' } as Record<string, string>,
    line: (who: string, verb: string, what: string) => `${who} ${verb} ${what}`,
    changed: (fields: string) => `(${fields})`,
  },
  // GOAL_2.0 P4.2: the toast when someone else in the shop adds an entry.
  live: {
    added: (who: string, what: string) => `${who} added ${what}`,
    someone: 'Someone',
    you: (name: string) => `${name} (you)`,
    member: 'Member',
  },
  time: {
    justNow: 'just now',
    minsAgo: (n: number) => `${n} min ago`,
    hoursAgo: (n: number) => `${n} h ago`,
    yesterday: 'yesterday',
  },
  // GOAL_2.0 P6.6: what an expense was for.
  categories: {
    title: 'Category',
    names: { stock_other: 'Shop supplies', rent: 'Rent', electricity: 'Electricity', wages: 'Wages',
      transport: 'Transport', repairs: 'Repairs', misc: 'Other', uncategorised: 'Uncategorised' } as Record<string, string>,
  },
  // GOAL_2.0 P6: every number here comes from SQL.
  dashboard: {
    heading: ['How the shop', 'is doing.'],
    today: 'Today',
    vs: (delta: string, day: string) => `${delta} vs ${day}`,
    same: (day: string) => `Same as ${day}`,
    chartsTitle: 'The last 30 days',
    salesVsCollections: 'Cash sales and collections',
    sales: 'Cash sales',
    collections: 'Collections',
    outstanding: 'Credit still owed to you',
    outstandingHelp: 'Worked out from every credit given and every payment received.',
    expensesTitle: 'Expenses by category, this month',
    expensesEmpty: 'No expenses this month yet.',
    chartSummary: (what: string, from: string, to: string) => `${what}, ${from} to ${to}. The same numbers are in the day-by-day table.`,
    register: {
      title: 'Day by day',
      help: 'The last 30 days, confirmed entries only. Weekly subtotals run Monday to Sunday.',
      caption: 'Day by day, last 30 days',
      cols: { day: 'Date', cash: 'Cash sales', credit: 'Credit given', collected: 'Collected', purchases: 'Purchases',
        supplierPaid: 'Supplier paid', expenses: 'Expenses', net: 'Net cash in hand' },
      netHelp: 'Net cash in hand = cash sales + collected − purchases paid in cash − supplier paid − expenses.',
      week: (from: string, to: string) => `Week ${from} – ${to}`,
      sort: (col: string) => `Sort by ${col}`,
    },
    aging: {
      title: 'Who owes me',
      help: 'Age = days since their last payment, or since their first credit if they have never paid.',
      caption: 'Customers who owe you, largest first',
      cols: { name: 'Name', balance: 'Owes you', oldest: 'Oldest due', lastPayment: 'Last payment', bucket: 'Age' },
      bucket: (b: string) => `${b} days`,
      days: (n: number) => (n === 1 ? '1 day' : `${n} days`),
      never: 'Never',
      total: (n: number) => (n === 1 ? '1 customer' : `${n} customers`),
      empty: 'Nobody owes you anything right now.',
    },
    dues: {
      title: 'What I owe',
      help: 'Days = since your last payment to them, or since the first purchase on credit if you have never paid.',
      caption: 'Suppliers you owe, largest first',
      cols: { name: 'Supplier', owed: 'You owe', lastPayment: 'Last payment', days: 'Days' },
      empty: 'You owe no supplier anything right now.',
    },
    top: {
      title: 'Top customers this month',
      byCredit: 'Most credit taken',
      byCollections: 'Most paid back',
      name: 'Name',
      amount: 'Amount',
      empty: 'No customer entries this month yet.',
    },
  },

  toast: {
    undo: 'Undo',
    undone: 'Undone.',
  },

  errors: {
    loading: 'Loading…',
    notFound: 'That page does not exist.',
    waking: 'Waking the server…',
    wakingHelp: 'The first request after a quiet spell can take up to a minute.',
  },

  offline: {
    heading: ['No internet.', 'Entries can’t be saved right now.'],
    retry: 'Retry',
    still: 'Still no connection. Check your internet, then retry.',
    network: 'No internet. Entries can’t be saved right now.',
  },
} as const
