// NEEDS NATIVE REVIEW. Hindi UI strings (GOAL_2.0 P5.2), written by the build agent, not a native
// speaker. Same keys as en.ts (the Strings type enforces it). Amounts, names and brand words are
// kept as in English. Two-line headings are [line1, line2].
import type { Strings } from '.'

export const hi: Strings = {
  brand: 'KHATA',
  arrow: '→',

  nav: {
    home: 'होम',
    ledger: 'खाता-बही',
    dashboard: 'डैशबोर्ड',
    parties: 'ग्राहक-सप्लायर',
    scan: 'स्कैन',
    review: 'जाँचें',
    settings: 'सेटिंग्स',
    menu: 'मेन्यू',
    close: 'बंद करें',
    main: 'मुख्य',
    reviewCount: (n: number) => `${n} जाँचने बाकी`,
  },

  auth: {
    heading: ['आपकी दुकान का खाता,', 'बोलकर।'],
    blurb: ['एंट्री बोलिए, बिल स्कैन कीजिए, बकाया पूछिए।', 'छह भारतीय भाषाएँ।'],
    sideLabel: 'छह भाषाएँ, एक खाता।',
    email: 'ईमेल',
    password: 'पासवर्ड',
    name: 'आपका नाम',
    logIn: 'लॉग इन',
    createAccount: 'खाता बनाएँ',
    toSignup: 'नए हैं? खाता बनाएँ',
    toLogin: 'पहले से खाता है? लॉग इन करें',
    working: 'हो रहा है…',
    show: 'दिखाएँ',
    hide: 'छिपाएँ',
    showPassword: 'पासवर्ड दिखाएँ',
    forgot: 'पासवर्ड भूल गए?',
    forgotHelp: 'अपना ईमेल लिखें। हम नया पासवर्ड रखने का लिंक भेजेंगे।',
    sendLink: 'लिंक भेजें',
    linkSent: 'अगर इस ईमेल से खाता है, तो नया पासवर्ड रखने का लिंक आ रहा है। अपना इनबॉक्स देखें।',
    newPassword: 'नया पासवर्ड',
    setPassword: 'नया पासवर्ड सेव करें',
    resetExpired: 'यह लिंक पुराना हो गया है या पहले इस्तेमाल हो चुका है। नया लिंक मँगाएँ।',
    askAgain: 'नया लिंक भेजें',
    sessionEnded: 'आपका सत्र ख़त्म हो गया। फिर से लॉग इन करें, आप वहीं लौटेंगे जहाँ थे।',
    errors: {
      required: 'यह भरना ज़रूरी है।',
      email: 'name@example.com जैसा ईमेल पता लिखें।',
      passwordShort: 'कम से कम 6 अक्षर रखें।',
      badLogin: 'ईमेल या पासवर्ड गलत है। दोनों जाँचकर फिर कोशिश करें।',
      exists: 'इस ईमेल से खाता पहले से है। लॉग इन करें।',
      emailDisabled: 'इस ऐप में ईमेल लॉग इन बंद है। जिसने इसे सेट किया है उनसे पूछें।',
      generic: 'सर्वर तक नहीं पहुँच पाए। इंटरनेट जाँचकर फिर कोशिश करें।',
    },
  },

  onboarding: {
    heading: ['अपनी दुकान', 'सेट करें।'],
    languageHeading: ['अपनी भाषा', 'चुनें।'],
    step: (n: number) => `चरण ${n} / 2`,
    create: 'दुकान बनाएँ',
    join: 'कोड से जुड़ें',
    shopName: 'दुकान का नाम',
    code: '6 अक्षर का निमंत्रण कोड',
    languageHelp: 'Khata इसी भाषा में सुनता, बोलता और स्क्रीन दिखाता है। सेटिंग्स में आप हर एक अलग से चुन सकते हैं।',
    next: 'आगे',
    back: 'पीछे',
    createShop: 'दुकान बनाएँ',
    joinShop: 'दुकान से जुड़ें',
    errors: {
      required: 'यह भरना ज़रूरी है।',
      codeLength: 'कोड में 6 अक्षर होते हैं।',
      pickLanguage: 'आगे बढ़ने के लिए भाषा चुनें।',
    },
  },

  languages: {
    'ta-IN': 'தமிழ்',
    'hi-IN': 'हिन्दी',
    'en-IN': 'English',
    'te-IN': 'తెలుగు',
    'kn-IN': 'ಕನ್ನಡ',
    'ml-IN': 'മലയാളം',
  },

  screens: {
    ledger: ['आपका', 'खाता।'],
    parties: ['ग्राहक', 'और सप्लायर।'],
    partyDetail: ['पार्टी का', 'ब्योरा।'],
    review: ['इन्हें', 'देख लें।'],
    entry: ['एंट्री', 'बदलें।'],
    scan: ['कैसा', 'बिल है?'],
    settings: ['आपकी', 'सेटिंग्स।'],
  },

  status: {
    confirmed: 'पक्का',
    pending: 'रुका हुआ',
    voided: 'रद्द',
    auto: 'अपने आप',
    new: 'नया',
  },

  ledger: {
    holdToAdd: 'दबाकर जोड़ें',
    holdToAsk: 'दबाकर पूछें',
    holdToAnswer: 'दबाकर जवाब दें',
    scanBill: 'बिल स्कैन करें',
    listening: 'सुन रहा हूँ… छोड़ें तो भेजूँ',
    working: 'हो रहा है…',
    tooShort: 'बोलते समय बटन दबाए रखें।',
    recent: ['हाल की', 'एंट्रियाँ।'],
    empty: ['जोड़ें दबाकर बताइए क्या हुआ,', 'जैसे ‘रमेश ने 250 उधार लिए’।'],
    confirm: 'पक्का करें',
    edit: 'बदलें',
    voidIt: 'रद्द करें',
    yesName: (name: string) => `हाँ, ${name}`,
    didYouMean: (name: string) => `क्या आपका मतलब ${name} था?`,
    noNewPerson: 'नहीं, नया व्यक्ति',
    addByHand: 'हाथ से जोड़ें',
    closeForm: 'फ़ॉर्म बंद करें',
    type: 'प्रकार',
    amount: 'रकम (₹)',
    partyName: 'ग्राहक या सप्लायर का नाम',
    note: 'नोट',
    save: 'एंट्री सेव करें',
    saved: (who: string, amount: string) => `सेव हुआ · ${who} · ${amount}`,
    whatIHeard: 'मैंने क्या सुना',
    heardNothing: 'कुछ नहीं। रिकॉर्डिंग में आवाज़ नहीं थी।',
    play: 'चलाएँ',
    noParty: '—',
  },

  table: {
    heading: ['पूरा', 'खाता।'],
    presets: { all: 'सब', today: 'आज', week: 'इस हफ़्ते', month: 'इस महीने', custom: 'अपनी तारीखें' },
    period: 'समय',
    from: 'से',
    to: 'तक',
    type: 'प्रकार',
    allTypes: 'सभी प्रकार',
    party: 'पार्टी',
    allParties: 'सभी',
    source: 'कैसे जुड़ा',
    allSources: 'कोई भी',
    member: 'किसने जोड़ा',
    allMembers: 'कोई भी',
    show: 'दिखाएँ',
    search: 'नाम और नोट में खोजें',
    cols: { date: 'तारीख', party: 'पार्टी', type: 'प्रकार', amount: 'रकम', source: 'कैसे जुड़ा', addedBy: 'किसने जोड़ा', status: 'स्थिति' },
    sources: { voice: 'आवाज़', receipt: 'बिल', manual: 'टाइप किया' },
    totals: { cashIn: 'नकद आया', credit: 'उधार दिया', collected: 'वसूला', expenses: 'खर्च',
      note: 'जोड़ में सिर्फ़ पक्की एंट्रियाँ गिनी जाती हैं।' },
    count: (n: number) => `${n} एंट्री`,
    page: (p: number, n: number) => `पेज ${p} / ${n}`,
    prev: 'पिछला',
    next: 'अगला',
    export: 'CSV डाउनलोड करें',
    exporting: 'तैयार हो रहा है…',
    empty: 'इन फ़िल्टर से कोई एंट्री नहीं मिली। फ़िल्टर हटाएँ या हाथ से जोड़ें।',
    clear: 'फ़िल्टर हटाएँ',
    caption: 'खाते की एंट्रियाँ, नई पहले',
    open: (what: string) => `${what} खोलें`,
  },

  manual: {
    date: 'तारीख',
    matches: 'मिलते-जुलते नाम',
    savedAddAnother: 'सेव हुआ। अगली जोड़ें।',
  },

  mic: {
    heading: ['माइक्रोफ़ोन', 'बंद है।'],
    lead: 'एंट्री और सवाल सुनने के लिए Khata को माइक्रोफ़ोन चाहिए। जब तक आप बटन नहीं दबाते, कुछ रिकॉर्ड नहीं होता।',
    steps: [
      'वेब पते के पास ताले या सेटिंग्स के निशान पर टैप करें।',
      'माइक्रोफ़ोन ढूँढें और अनुमति दें चुनें।',
      'यहाँ लौटकर फिर कोशिश करें पर टैप करें।',
    ],
    retry: 'फिर कोशिश करें',
    close: 'बंद करें',
  },

  landing: {
    nav: { home: 'होम', how: 'यह कैसे काम करता है', login: 'लॉग इन', start: 'शुरू करें' },
    hero: ['आपका खाता,', 'बोलकर।'],
    blurb: ['एंट्री बोलिए, बिल स्कैन कीजिए, बकाया पूछिए।', 'छह भारतीय भाषाएँ।'],
    start: 'शुरू करें',
    howTitle: ['खाता रखने के', 'तीन तरीके।'],
    ways: [
      { title: 'बोलिए', body: ['दबाइए, बताइए किसने क्या लिया।', 'लिख लिया जाएगा।'] },
      { title: 'स्कैन कीजिए', body: ['कोई भी बिल खींचिए,', 'छपा हो या हाथ से लिखा।'] },
      { title: 'पूछिए', body: ['‘रमेश पर कितना बाकी है?’', 'जवाब बोलकर मिलेगा।'] },
    ],
    trustTitle: ['भरोसे के लिए', 'बनाया गया।'],
    principles: ['हर एंट्री के साथ उसकी रिकॉर्डिंग रहती है।', 'बड़ी रकम हमेशा आपके टैप का इंतज़ार करती है।', 'छह भाषाएँ, एक खाता।'],
    sayTitle: ['अपने ढंग से', 'बोलिए।'],
    sayLines: [
      { said: 'ரமேஷுக்கு 250 ரூபாய் கடன் கொடுத்தேன்', lang: 'तमिल', code: 'ta' },
      { said: 'रमेश को 250 उधार दिया', lang: 'हिन्दी', code: 'hi' },
      { said: 'Gave Ramesh 250 on credit', lang: 'अंग्रेज़ी', code: 'en' },
      { said: 'రమేష్‌కి 250 రూపాయలు అప్పు ఇచ్చాను', lang: 'तेलुगु', code: 'te' },
      { said: 'ರಮೇಶ್‌ಗೆ 250 ರೂಪಾಯಿ ಸಾಲ ಕೊಟ್ಟೆ', lang: 'कन्नड़', code: 'kn' },
      { said: 'രമേശിന് 250 രൂപ കടം കൊടുത്തു', lang: 'मलयालम', code: 'ml' },
    ],
    builtByTitle: ['किसने', 'बनाया।'],
    builtByBio: [],
    footerLinks: [
      { label: 'लॉग इन', to: '/login' },
      { label: 'खाता बनाएँ', to: '/signup' },
      { label: 'यह कैसे काम करता है, विस्तार से', to: '/about' },
    ],
    builtFor: 'Sarvam Campus Builds, सितंबर 2026 के लिए बनाया गया।',
    repoLabel: 'github.com/maanit-gupta/KHATA',
    repoUrl: 'https://github.com/maanit-gupta/KHATA',
    founderAlt: 'Khata बनाने वाले',
  },

  about: {
    navSignup: 'साइन अप',
    navLogin: 'लॉग इन',
    hero: ['Khata कैसे', 'काम करता है।'],
    intro:
      'Khata किराना और छोटी दुकानों के लिए खाता है। एंट्री बोलिए या बिल की फ़ोटो लीजिए; Khata उसे खाते में लिखता है, सही ग्राहक या सप्लायर से मिलाता है, और आपकी भाषा में पढ़कर सुनाता है।',
    flowTitle: ['जोड़ने के', 'दो तरीके।'],
    flows: [
      {
        label: 'बोलिए',
        title: 'दबाइए, बोलिए, छोड़िए।',
        steps: [
          'बटन दबाकर बताइए किसने क्या लिया, जैसे “रमेश को 250 उधार दिया”। 30 सेकंड तक।',
          'रिकॉर्डिंग निजी रूप से रखी जाती है, फिर Sarvam आवाज़ को अंग्रेज़ी पाठ में बदलता है।',
          'Groq उस पाठ से प्रकार, व्यक्ति और रकम सख़्त JSON में निकालता है।',
          'नाम आपके ग्राहकों या सप्लायरों से मिलाया जाता है, और नीचे दिए नियम तय करते हैं कि आगे क्या होगा।',
          'Khata नतीजा आपकी भाषा में बोलता है: “रमेश, 250 रुपये उधार, सेव हुआ।”',
        ],
      },
      {
        label: 'स्कैन कीजिए',
        title: 'बिल की फ़ोटो लीजिए।',
        steps: [
          'बताइए बिल किस तरह का है: सप्लायर, ग्राहक या खर्च।',
          'बताइए हिसाब कैसे हुआ: सप्लायर के लिए चुकाया या उधार, ग्राहक के लिए नकद या उधार।',
          'फ़ोटो लीजिए या अपलोड कीजिए। Sarvam Document AI विक्रेता, तारीख और कुल रकम पढ़ता है।',
          'सेव करने से पहले तीनों खाने जाँचिए और ठीक कीजिए। बिल न पढ़ा जाए तो खुद लिखिए।',
          'बिल सही प्रकार की एंट्री बन जाता है, और वही सेव नियम लागू होते हैं।',
        ],
      },
    ],
    rulesTitle: ['क्या सेव हो,', 'कौन तय करता है।'],
    rulesLead:
      'AI नहीं। मॉडल सिर्फ़ पढ़ता है कि क्या कहा गया। सादे कोड में लिखे कुछ तय नियम तय करते हैं कि एंट्री सेव हो, आपका इंतज़ार करे, या फिर से पूछा जाए।',
    rules: [
      { when: 'रकम नहीं, या जहाँ नाम चाहिए वहाँ नाम नहीं', result: 'फिर पूछता है', status: 'unselected' },
      { when: 'नाम साफ़ तौर पर एक ग्राहक या सप्लायर से मिलता है', result: 'उसी को लेता है', status: 'confirmed' },
      { when: 'नाम किसी से मिलता-जुलता है, पर पक्का नहीं', result: 'क्या आपका मतलब…?', status: 'pending' },
      { when: 'ऐसा नाम जो Khata ने कभी नहीं सुना', result: 'नया, निशान लगा', status: 'confirmed' },
      { when: '₹5,000 से ज़्यादा', result: 'टैप का इंतज़ार', status: 'pending' },
      { when: 'बाकी सब', result: 'सेव, 5 सेकंड में वापस ले सकते हैं', status: 'confirmed' },
    ],
    legend: { saved: 'सेव हुआ', pending: 'आपका इंतज़ार', nothing: 'कुछ सेव नहीं' },
    trustTitle: ['भरोसे के लिए', 'बनाया गया।'],
    trust: [
      { title: 'हर एंट्री का सबूत रहता है', body: 'आवाज़ का नोट या बिल की फ़ोटो एंट्री के साथ निजी स्टोरेज में रहती है, ताकि बाद में झगड़ा हो तो काम आए।' },
      { title: 'कुछ भी मिटाया नहीं जाता', body: 'गलत एंट्री रद्द होती है, मिटती नहीं; हर बदलाव किसने किया और क्या बदला, दर्ज रहता है।' },
      { title: 'बड़ी रकम आपका इंतज़ार करती है', body: '₹5,000 से ऊपर कुछ भी तब तक रुका रहता है जब तक दुकान का कोई व्यक्ति पक्का करें न दबाए।' },
      { title: 'सिर्फ़ आपकी दुकान', body: 'डेटाबेस की row-level security से हर सदस्य सिर्फ़ अपनी दुकान का खाता पढ़ सकता है।' },
      { title: 'अंक दो बार जाँचे जाते हैं', body: 'पढ़कर सुनाई बातें आपकी भाषा में अनुवाद होती हैं; अगर रास्ते में कोई अंक बदल जाए, तो Khata अंग्रेज़ी में बोलता है।' },
      { title: 'पूरे पैसे में हिसाब', body: 'रकम पूरे पैसे में रखी जाती है, दशमलव में नहीं, और बाकी हमेशा एंट्रियों से ही निकाला जाता है।' },
    ],
    langTitle: ['अपने ढंग से', 'बोलिए।'],
    langLead: 'दुकान का हर व्यक्ति अपनी भाषा चुनता है। बोलना और सुनना उसी में होता है; नाम वैसे ही रहते हैं जैसे लिखे गए।',
    examples: [
      { said: 'रमेश को 250 उधार दिया', lang: 'हिन्दी' },
      { said: 'ரமேஷுக்கு 250 ரூபாய் கடன் கொடுத்தேன்', lang: 'तमिल' },
      { said: 'రమేష్‌కి 250 రూపాయలు అప్పు ఇచ్చాను', lang: 'तेलुगु' },
      { said: 'ರಮೇಶ್‌ಗೆ 250 ರೂಪಾಯಿ ಸಾಲ ಕೊಟ್ಟೆ', lang: 'कन्नड़' },
      { said: 'രമേശിന് 250 രൂപ കടം കൊടുത്തു', lang: 'मलयालम' },
      { said: 'Gave Ramesh 250 on credit', lang: 'अंग्रेज़ी' },
    ],
    stackTitle: ['किससे', 'बना है।'],
    stack: [
      ['आवाज़ और बिल', 'Sarvam AI: saaras:v3 speech-to-text, mayura translation, bulbul:v3 voices, Document AI extract'],
      ['समझ', 'Groq पर gpt-oss-20b एंट्री पढ़ने के लिए, gpt-oss-120b सवालों के जवाब के लिए'],
      ['डेटा और खाते', 'Supabase: row-level security वाला Postgres, ईमेल लॉग इन, निजी फ़ाइल स्टोरेज'],
      ['ऐप', 'Vercel पर React और Vite, Render पर FastAPI (Python) बैकएंड'],
    ],
    ctaTitle: ['खुद', 'देखिए।'],
    ctaBody: 'खाता बनाइए, दुकान सेट कीजिए, और जोड़ें दबाकर पहली एंट्री बोलिए।',
    ctaSignup: 'खाता बनाएँ',
    repo: 'GitHub पर सोर्स',
    repoUrl: 'https://github.com/maanit-gupta/KHATA',
    link: 'यह कैसे काम करता है',
  },

  scan: {
    kindHeading: ['कैसा', 'बिल है?'],
    settleHeading: ['हिसाब कैसे', 'हुआ?'],
    photoHeading: ['बिल की', 'फ़ोटो लें।'],
    previewHeading: ['बिल साफ़', 'दिख रहा है?'],
    readingHeading: ['बिल पढ़ा', 'जा रहा है।'],
    checkHeading: ['बिल', 'जाँचें।'],
    doneHeading: ['बिल', 'सेव हुआ।'],
    supplier: 'सप्लायर',
    customer: 'ग्राहक',
    expense: 'खर्च',
    kindHelp: {
      supplier: 'थोक वाले से खरीदा माल।',
      customer: 'ग्राहक को दिया गया बिल।',
      expense: 'किराया, बिजली, तनख़्वाह और दूसरे खर्च।',
    },
    paid: 'चुकाया',
    credit: 'उधार',
    cash: 'नकद',
    udhaar: 'उधार',
    takePhoto: 'फ़ोटो लें',
    fromGallery: 'गैलरी से अपलोड करें',
    chooseFile: 'फ़ाइल चुनें',
    dropHere: 'बिल की फ़ोटो या PDF यहाँ छोड़ें',
    photoHelp: 'JPG, PNG, HEIC या एक पेज का PDF, 10 MB तक।',
    errors: {
      type: 'यह फ़ाइल फ़ोटो या PDF नहीं है। बिल का JPG, PNG, HEIC या PDF लें।',
      heic: 'यह ब्राउज़र HEIC फ़ोटो नहीं खोल सकता। फ़ोटो लें दबाएँ, या iPhone में Settings → Camera → Formats → Most Compatible चुनें।',
      size: 'यह फ़ाइल 10 MB से बड़ी है। छोटी फ़ोटो लें।',
      decode: 'यह फ़ोटो खुल नहीं पाई। फिर से लें।',
    },
    rotate: '90° घुमाएँ',
    retake: 'फिर से लें',
    usePhoto: 'यही फ़ोटो लें',
    tooDarkOrSmall: 'फ़ोटो बहुत अँधेरी या छोटी है; ठीक से पढ़ने के लिए फिर से लें।',
    pdfFile: (name: string) => `PDF · ${name}`,
    steps: { uploading: 'अपलोड हो रहा है', reading: 'बिल पढ़ा जा रहा है', checking: 'जाँच हो रही है' },
    cancel: 'रद्द करें',
    slow: 'इसमें आम से ज़्यादा समय लग रहा है।',
    typeItIn: 'इसके बजाय खुद लिखें',
    typeByHand: 'बिल से रकम और बाकी चीज़ें लिखें।',
    vendor: 'विक्रेता',
    date: 'बिल की तारीख',
    total: 'कुल (₹)',
    customerName: 'ग्राहक का नाम',
    notFound: 'नहीं मिला, कृपया लिखें।',
    dateNotFound: 'बिल पर नहीं मिली; आज की तारीख भर दी है।',
    checkThis: 'इसे जाँचें: यह कुल रकम पढ़े गए बिल पर छपी नहीं मिली।',
    changeKind: 'बिल का प्रकार',
    save: 'एंट्री सेव करें',
    saved: 'सेव हुआ।',
    pending: 'टैप का इंतज़ार। यहाँ या जाँचें में पक्का करें।',
    another: 'दूसरा बिल',
    back: 'पीछे',
    toLedger: 'खाते पर वापस',
    preview: 'बिल की फ़ोटो',
    enlarge: 'फ़ोटो बड़ी करें',
    shrink: 'फ़ोटो छोटी करें',
    whatIRead: 'मैंने क्या पढ़ा',
    readNothing: 'इस फ़ोटो से कोई पाठ नहीं पढ़ा जा सका।',
  },

  entryTypes: {
    credit_given: 'उधार दिया',
    payment_received: 'पैसा मिला',
    cash_sale: 'नकद बिक्री',
    purchase_credit: 'उधार पर खरीद',
    purchase_paid: 'नकद खरीद',
    payment_made: 'भुगतान किया',
    expense: 'खर्च',
  },

  parties: {
    owesYou: (amount: string) => `आपको ${amount} देने हैं`,
    youOwe: (amount: string) => `आपको ${amount} चुकाने हैं`,
    settled: 'हिसाब बराबर',
    empty: 'अभी कोई ग्राहक या सप्लायर नहीं। एंट्री जोड़ने पर दिखेंगे।',
    noMatch: 'इस नाम का कोई नहीं।',
    back: 'सभी पार्टियाँ',
    search: 'नाम से खोजें',
    filter: 'ग्राहक या सप्लायर दिखाएँ',
    customers: 'ग्राहक',
    suppliers: 'सप्लायर',
    playRecording: 'रिकॉर्डिंग चलाएँ',
    openBill: 'बिल की फ़ोटो खोलें',
    noEntries: 'अभी कोई एंट्री नहीं।',
    customer: 'ग्राहक',
    supplier: 'सप्लायर',
    statement: {
      title: 'हिसाब का ब्योरा',
      from: 'से',
      to: 'तक',
      cols: { date: 'तारीख', description: 'विवरण', change: '+ / −', balance: 'इसके बाद बाकी' },
      opening: 'शुरुआती बाकी',
      closing: 'आख़िरी बाकी',
      share: 'ब्योरा भेजें',
      empty: 'इन तारीखों में कोई पक्की एंट्री नहीं।',
      caption: (name: string) => `${name} का ब्योरा, पुरानी पहले`,
      help: '+ का मतलब उन पर दुकान का ज़्यादा बाकी; − का मतलब कम। सिर्फ़ पक्की एंट्रियाँ।',
    },
    entriesTitle: 'एंट्रियाँ',
    edit: 'नाम या प्रकार बदलें',
    closeEdit: 'बंद करें',
    name: 'नाम',
    kind: 'प्रकार',
    save: 'सेव करें',
    saved: 'सेव हुआ।',
    kindLocked: (kind: string) => `इसकी एंट्रियाँ हैं, इसलिए यह ${kind} ही रहेगा: बदलने से हर एंट्री का मतलब बदल जाएगा।`,
    exists: (name: string) => `पहले से है: ${name}।`,
    openIt: 'खोलें',
  },

  week: {
    heading: ['इस हफ़्ते,', 'अब तक।'],
    cash: 'नकद बिक्री',
    credit: 'उधार दिया',
    collected: 'वसूला',
    expenses: 'खर्च',
    lastWeek: (amount: string) => `पिछला हफ़्ता, सोम–रवि: ${amount}`,
    debtors: 'सबसे ज़्यादा बाकी',
    days: (n: number | null) => (n === null ? '' : n === 0 ? 'आख़िरी एंट्री आज' : `आख़िरी एंट्री ${n} दिन पहले`),
    play: 'सारांश सुनें',
  },

  review: {
    pendingTitle: 'टैप का इंतज़ार',
    partiesTitle: 'नए लोग',
    receiptsTitle: 'जो बिल पढ़े नहीं जा सके',
    empty: 'अभी कुछ देखने को नहीं।',
    rename: 'नाम बदलें',
    mergeInto: 'इसमें मिलाएँ…',
    keep: 'जैसा है रहने दें',
    saveName: 'नाम सेव करें',
    cancel: 'रद्द करें',
    newName: 'नया नाम',
    mergePick: (name: string) => `${name} को इसमें मिलाएँ:`,
    noMergeTarget: 'मिलाने के लिए इस तरह का कोई और नहीं है।',
    merged: (from: string, into: string) => `${from} को ${into} में मिला दिया।`,
    enterManually: 'खुद लिखें',
    unreadBill: (kind: string) => `${kind} बिल`,
  },

  entry: {
    heading: ['एंट्री', 'बदलें।'],
    saveChanges: 'बदलाव सेव करें',
    saved: 'बदलाव सेव हुए।',
    party: 'ग्राहक या सप्लायर',
    date: 'तारीख',
    historyTitle: 'इतिहास',
    actions: { create: 'बनाई', edit: 'बदली', confirm: 'पक्की की', void: 'रद्द की' },
    fields: {
      amount_paise: 'रकम', type: 'प्रकार', party: 'पार्टी', occurred_on: 'तारीख', note: 'नोट', status: 'स्थिति',
    },
    addedBy: (name: string) => `${name} ने जोड़ी`,
    confirmedBy: (name: string) => `${name} ने पक्की की`,
    voidEntry: 'एंट्री रद्द करें',
    voidConfirmTitle: 'यह एंट्री रद्द करें?',
    voidConfirmBody: 'यह बाकी और जोड़ में नहीं गिनी जाएगी। इतिहास में रहेगी और बाद में बदली नहीं जा सकेगी।',
    voidYes: 'हाँ, रद्द करें',
    keepIt: 'रहने दें',
    voided: 'यह एंट्री रद्द है। अब गिनी नहीं जाती।',
    source: { voice: 'बोलकर', receipt: 'बिल से', manual: 'टाइप करके' },
    none: 'कुछ नहीं',
  },

  settings: {
    languages: {
      title: 'भाषाएँ',
      help: 'हर एक अलग से चुनें। बदलाव तुरंत लागू होते हैं।',
      ui: 'स्क्रीन की भाषा',
      uiHelp: 'बटन, लेबल और संदेश।',
      speak: 'मैं बोलता/बोलती हूँ',
      speakHelp: 'जिस भाषा में आप Khata से बात करते हैं।',
      auto: 'अपने आप पहचानें',
      autoHelp: 'Khata खुद समझ लेता है कि आपने कौन सी भाषा बोली।',
      voice: 'पढ़कर सुनाना और जवाब',
      voiceHelp: 'Khata जो बोलकर सुनाता है।',
      report: 'सारांश और रिपोर्ट',
      reportHelp: 'हफ़्ते का सारांश, सुझाव, रोज़ की जानकारी और PDF रिपोर्ट।',
    },
    voice: 'आवाज़',
    voiceHelp: 'सुनने के लिए किसी आवाज़ पर टैप करें।',
    defaultVoice: 'डिफ़ॉल्ट',
    sample: 'Ramesh owes you 250 rupees.',
    invite: 'दुकान का निमंत्रण कोड',
    inviteHelp: 'इस कोड वाला कोई भी आपकी दुकान से जुड़ सकता है।',
    copy: 'कॉपी',
    copied: 'कॉपी हुआ',
    logOut: 'लॉग आउट',
    shop: 'दुकान',
    name: 'मेरा नाम',
    nameHelp: 'आप जो जोड़ें या बदलें, उसके पास दुकान के सब लोग यह नाम देखते हैं।',
    saveName: 'नाम सेव करें',
    nameSaved: 'नाम सेव हुआ।',
    members: 'इस दुकान के लोग',
    roles: { owner: 'मालिक', staff: 'स्टाफ़' },
    joined: (day: string) => `${day} को जुड़े`,
    sameRights: 'दुकान में सब लोग एक जैसे काम कर सकते हैं।',
  },

  activity: {
    title: 'क्या हुआ',
    empty: 'अभी कुछ नहीं। हर जोड़ी, बदली, पक्की या रद्द की गई एंट्री यहाँ दिखेगी, करने वाले के नाम के साथ।',
    verbs: { create: 'ने जोड़ी', edit: 'ने बदली', confirm: 'ने पक्की की', void: 'ने रद्द की' },
    line: (who: string, verb: string, what: string) => `${who} ${verb}: ${what}`,
    changed: (fields: string) => `(${fields})`,
  },
  live: {
    added: (who: string, what: string) => `${who} ने जोड़ा: ${what}`,
    someone: 'किसी ने',
    you: (name: string) => `${name} (आप)`,
    member: 'सदस्य',
  },
  time: {
    justNow: 'अभी',
    minsAgo: (n: number) => `${n} मिनट पहले`,
    hoursAgo: (n: number) => `${n} घंटे पहले`,
    yesterday: 'कल',
  },
  categories: {
    title: 'श्रेणी',
    names: { stock_other: 'दुकान का सामान', rent: 'किराया', electricity: 'बिजली', wages: 'तनख़्वाह',
      transport: 'आना-जाना', repairs: 'मरम्मत', misc: 'अन्य', uncategorised: 'बिना श्रेणी' },
  },
  dashboard: {
    heading: ['दुकान', 'कैसी चल रही है।'],
    emptyShop: 'एंट्री जोड़ने के साथ यह भरता जाएगा। होम पर जोड़ें दबाकर बोलें, बिल स्कैन करें, या खाता-बही में हाथ से जोड़ें।',
    today: 'आज',
    vs: (delta: string, day: string) => `${day} के मुकाबले ${delta}`,
    same: (day: string) => `${day} जितना`,
    chartsTitle: 'पिछले 30 दिन',
    salesVsCollections: 'नकद बिक्री और वसूली',
    sales: 'नकद बिक्री',
    collections: 'वसूली',
    outstanding: 'बाज़ार में बकाया उधार',
    outstandingHelp: 'हर दिए गए उधार और हर मिली रकम से निकाला गया।',
    expensesTitle: 'इस महीने के खर्च, श्रेणी के हिसाब से',
    expensesEmpty: 'इस महीने अभी कोई खर्च नहीं।',
    chartSummary: (what: string, from: string, to: string) => `${what}, ${from} से ${to} तक। यही अंक रोज़ के हिसाब वाली तालिका में हैं।`,
    register: {
      title: 'रोज़ का हिसाब',
      help: 'पिछले 30 दिन, सिर्फ़ पक्की एंट्रियाँ। हफ़्ते का जोड़ सोमवार से रविवार।',
      caption: 'रोज़ का हिसाब, पिछले 30 दिन',
      cols: { day: 'तारीख', cash: 'नकद बिक्री', credit: 'उधार दिया', collected: 'वसूला', purchases: 'खरीद',
        supplierPaid: 'सप्लायर को दिया', expenses: 'खर्च', net: 'हाथ में नकद' },
      netHelp: 'हाथ में नकद = नकद बिक्री + वसूली − नकद खरीद − सप्लायर को दिया − खर्च।',
      week: (from: string, to: string) => `हफ़्ता ${from} – ${to}`,
      sort: (col: string) => `${col} से क्रम लगाएँ`,
    },
    aging: {
      title: 'किस पर कितना बाकी',
      help: 'उम्र = उनके आख़िरी भुगतान से दिन, या अगर कभी नहीं चुकाया तो पहले उधार से।',
      caption: 'जिन ग्राहकों पर बाकी है, सबसे बड़ी रकम पहले',
      cols: { name: 'नाम', balance: 'बाकी', oldest: 'सबसे पुराना बाकी', lastPayment: 'आख़िरी भुगतान', bucket: 'उम्र' },
      bucket: (b: string) => `${b} दिन`,
      days: (n: number) => `${n} दिन`,
      never: 'कभी नहीं',
      total: (n: number) => `${n} ग्राहक`,
      empty: 'अभी किसी पर कुछ बाकी नहीं।',
    },
    dues: {
      title: 'मुझे कितना देना है',
      help: 'दिन = उन्हें आपके आख़िरी भुगतान से, या अगर कभी नहीं चुकाया तो पहली उधार खरीद से।',
      caption: 'जिन सप्लायरों को देना है, सबसे बड़ी रकम पहले',
      cols: { name: 'सप्लायर', owed: 'देना है', lastPayment: 'आख़िरी भुगतान', days: 'दिन' },
      empty: 'अभी किसी सप्लायर का कुछ बाकी नहीं।',
    },
    top: {
      title: 'इस महीने के बड़े ग्राहक',
      byCredit: 'सबसे ज़्यादा उधार लिया',
      byCollections: 'सबसे ज़्यादा चुकाया',
      name: 'नाम',
      amount: 'रकम',
      empty: 'इस महीने अभी किसी ग्राहक की एंट्री नहीं।',
    },
  },

  reports: {
    summaryTitle: 'संक्षेप में',
    tabs: { day: 'आज', week: 'इस हफ़्ते', month: 'इस महीने' },
    tipsTitle: 'ध्यान देने लायक',
    noTips: 'अभी किसी बात पर ध्यान देने की ज़रूरत नहीं।',
    refresh: 'फिर से लिखें',
    refreshing: 'लिखा जा रहा है…',
    written: (time: string) => `${time} पर दुकान के आँकड़ों से लिखा गया; इसका हर अंक उन्हीं से जाँचा गया है।`,
    open: 'छापने लायक रिपोर्ट',
    heading: ['दुकान की', 'रिपोर्ट।'],
    period: 'समय',
    download: 'PDF डाउनलोड करें',
    printHelp: 'प्रिंट की खिड़की खुलेगी। कॉपी रखने के लिए “Save as PDF” चुनें।',
    footer: (shop: string, range: string, at: string) => `${shop} · ${range} · KHATA ने ${at} पर बनाया`,
    totalsTitle: 'कुल',
    expensesTitle: 'श्रेणी के हिसाब से खर्च',
    statementTitle: (name: string) => `हिसाब का ब्योरा: ${name}`,
    back: 'डैशबोर्ड पर वापस',
  },
  briefing: {
    title: 'आज की जानकारी',
    play: 'जानकारी सुनें',
    close: 'बंद करें',
  },

  toast: {
    undo: 'वापस लें',
    undone: 'वापस ले लिया।',
  },

  errors: {
    loading: 'लोड हो रहा है…',
    notFound: 'यह पेज मौजूद नहीं है।',
    waking: 'सर्वर जगाया जा रहा है…',
    wakingHelp: 'कुछ देर शांत रहने के बाद पहली बार में एक मिनट तक लग सकता है।',
  },

  offline: {
    heading: ['इंटरनेट नहीं है।', 'अभी एंट्री सेव नहीं हो सकती।'],
    retry: 'फिर कोशिश करें',
    still: 'अब भी कनेक्शन नहीं। इंटरनेट जाँचें, फिर कोशिश करें।',
    network: 'इंटरनेट नहीं है। अभी एंट्री सेव नहीं हो सकती।',
  },
}
