/**
 * GOAL_2.0 P7: the summary + tips card, the daily briefing card, and the printable report (period
 * and party statement), with PDF output in Tamil and Hindi. The backend's number guard, caches and
 * tip rules are tested in backend/tests/test_reports.py; here the API is mocked.
 */
import { mkdirSync, statSync } from 'node:fs'
import { expect, test, type Page } from '@playwright/test'
import { lastCall, open, shots } from './helpers'
import { MockApi } from './mock'

const PDF_DIR = new URL('../../artifacts/reports/', import.meta.url).pathname

test('summary card: today and this week, tips, write it again (then refused for 5 minutes)', async ({ page }) => {
  const m = new MockApi().seed()
  m.langs.report_lang = 'en-IN'           // this member speaks Hindi; reports chosen in English
  m.tips = [{ rule: 'overdue_customer', text: 'Arjun owes 800 rupees, 40 days since they first took credit. Ask for a payment.' }]
  await open(page, m, '/app/dashboard')
  const card = page.getByTestId('summary-card')
  await expect(card.getByTestId('summary-text')).toHaveText('Today so far you sold 300 rupees in cash.')
  await expect(card.getByTestId('tips').locator('li')).toHaveCount(1)
  await expect(card.getByTestId('tips').locator('li').first()).toHaveAttribute('data-rule', 'overdue_customer')
  await expect(card).toContainText('every number in it is checked')
  await card.getByRole('button', { name: 'This week' }).click()
  await expect(card.getByTestId('summary-text')).toHaveText('This week so far you sold 450 rupees in cash.')
  expect(lastCall(m, 'GET', '/reports/summary')?.path).toContain('period=week')
  await card.getByRole('button', { name: 'Write it again' }).click()
  await expect.poll(() => lastCall(m, 'POST', '/reports/summary/refresh')?.body).toEqual({ period: 'week' })
  await card.getByRole('button', { name: 'Write it again' }).click()
  await expect(card.getByRole('alert')).toContainText('refresh it again in 5 min')
  await shots(page, 'P7-reports', 'summary-card')
})

test('summary in the report language while the screens stay English', async ({ page }) => {
  const m = new MockApi().seed()
  m.langs.report_lang = 'ta-IN'
  await open(page, m, '/app/dashboard')
  await expect(page.getByTestId('summary-text')).toHaveText('[ta-IN] Today so far you sold 300 rupees in cash.')
  await expect(page.getByTestId('summary-text')).toHaveAttribute('lang', 'ta-IN')
  await expect(page.getByRole('heading', { name: 'In short' })).toBeVisible()
})

test('daily briefing: shown on Home, played on a tap (never autoplay), closed for the rest of the day', async ({ page }) => {
  const m = new MockApi().seed()
  m.langs.report_lang = 'hi-IN'
  await open(page, m, '/app')
  const card = page.getByTestId('briefing-card')
  await expect(card.getByTestId('briefing-text')).toHaveText(`[hi-IN] ${m.briefingText}`)
  expect(m.briefingAudio).toBe(0)                                   // nothing plays by itself
  await shots(page, 'P7-reports', 'briefing-home')
  await card.getByRole('button', { name: 'Play the briefing' }).click()
  await expect.poll(() => m.briefingAudio).toBe(1)
  await card.getByRole('button', { name: 'Close' }).click()
  await expect(card).toHaveCount(0)
  await page.reload()
  await expect(page.getByRole('button', { name: 'Hold to add' })).toBeVisible()
  await expect(page.getByTestId('briefing-card')).toHaveCount(0)
  await page.goto('/app/dashboard')
  await expect(page.getByTestId('today-strip')).toBeVisible()
  await expect(page.getByTestId('briefing-card')).toHaveCount(0)
})

async function printable(page: Page) {
  await page.evaluate(() => document.fonts.ready)
  await page.emulateMedia({ media: 'print' })
}

test('printable report: summary, totals, charts, register, aging, dues, footer; DOWNLOAD PDF prints', async ({ page }) => {
  const m = new MockApi().seed()
  m.langs.report_lang = 'en-IN'
  m.tips = [{ rule: 'supplier_unchanged', text: 'You owe Lotus Agencies 600 rupees, unchanged for 35 days.' }]
  await open(page, m, '/app/report?period=week')
  const report = page.getByTestId('report')
  await expect(report.getByTestId('report-summary')).toContainText('This week so far you sold 450 rupees in cash.')
  await expect(report.getByTestId('report-summary')).toContainText('You owe Lotus Agencies 600 rupees')
  await expect(report.getByTestId('report-totals')).toContainText('Net cash in hand')
  await expect(report.getByTestId('report-aging')).toContainText('Arjun')
  await expect(report.getByTestId('report-dues')).toContainText('Lotus Agencies')
  await expect(report.getByTestId('report-footer')).toContainText('Sharma Kirana')
  await expect(report.getByTestId('report-footer')).toContainText('Generated by KHATA')
  await page.evaluate(() => { (window as unknown as { printed: number }).printed = 0; window.print = () => { (window as unknown as { printed: number }).printed++ } })
  await page.getByRole('button', { name: 'Download PDF' }).click()
  expect(await page.evaluate(() => (window as unknown as { printed: number }).printed)).toBe(1)
  // Month: the 1st to today, and a custom range drops the written summary (it covers the current period).
  await page.getByRole('button', { name: 'This month' }).click()
  await expect(page.getByTestId('report-range')).toContainText('1 ')
  await printable(page)
  await expect(page.getByTestId('report-controls')).toBeHidden()
  await expect(page.locator('header nav, [aria-label="Main"]').first()).toBeHidden()
  await shots(page, 'P7-reports', 'report-print')
})

for (const [lang, word] of [['ta-IN', 'அறிக்கை'], ['hi-IN', 'रिपोर्ट']] as const) {
  test(`PDF in ${lang}: the report prints to A4 in its own script`, async ({ page }) => {
    const m = new MockApi().seed()
    m.langs.ui_lang = lang
    m.langs.report_lang = lang
    m.tips = [{ rule: 'overdue_customer', text: 'Arjun owes 800 rupees, 70 days since they first took credit. Ask for a payment.' }]
    await m.install(page)
    await page.context().unroute('https://fonts.googleapis.com/**')     // the real web fonts for this one
    await page.goto('/app/report?period=week')
    await expect(page.getByTestId('report').getByRole('heading', { level: 1 })).toContainText(word)
    await expect(page.getByTestId('report-summary')).toContainText(`[${lang}]`)
    await printable(page)
    mkdirSync(PDF_DIR, { recursive: true })
    const path = `${PDF_DIR}report-${lang.slice(0, 2)}.pdf`
    const pdf = await page.pdf({ path, format: 'A4', printBackground: true, preferCSSPageSize: true })
    expect(pdf.subarray(0, 5).toString()).toBe('%PDF-')
    expect(statSync(path).size).toBeGreaterThan(20_000)
    // Every glyph comes from a font that shapes this script (the design's Noto face when the web
    // fonts load, else the system's), never the last-resort box font.
    const fonts = [...pdf.toString('latin1').matchAll(/\/BaseFont\s*\/[A-Z]{6}\+([^\s/>\]]+)/g)].map((x) => x[1])
    expect(fonts.some((f) => f.includes(lang === 'ta-IN' ? 'Tamil' : 'Devanagari'))).toBe(true)
    expect(fonts.some((f) => /LastResort/i.test(f))).toBe(false)
    await page.screenshot({ path: `${PDF_DIR}report-${lang.slice(0, 2)}-print.png`, fullPage: true })
  })
}

test('party statement report', async ({ page }) => {
  const m = new MockApi().seed()
  const ramesh = m.parties.find((p) => p.display_name === 'Ramesh')!.id
  await open(page, m, `/app/report?party=${ramesh}`)
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Statement: Ramesh')
  await expect(page.getByTestId('statement-table')).toBeVisible()
  await expect(page.getByTestId('statement-closing')).toHaveText('Owes you ₹1,800')
  await expect(page.getByTestId('report-footer')).toContainText('Generated by KHATA')
  await printable(page)
  await shots(page, 'P7-reports', 'statement-print')
})
